name: Docker Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 4 * * *"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: make build

    - name: Test Docker image
      run: make test

    - name: Login to Docker Registry
      run: docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" "${{ secrets.REGISTRY_HOST }}"

    - name: Push Docker image
      run: make push
